# Generated by Django 4.2.13 on 2024-06-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0003_subscriber_subscribe_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='subscribe_type',
            field=models.CharField(choices=[('W', 'Subscribe Weekly'), ('M', 'Subscribe Monthly')], default='W', max_length=1),
        ),
    ]
