# Generated by Django 4.2.13 on 2024-06-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
