# Generated by Django 4.2.13 on 2024-06-16 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobmanager', '0004_author_location_jobpost_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='company',
        ),
    ]
