# Generated by Django 4.2.13 on 2024-06-18 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobmanager', '0007_remove_author_name_author_user_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='available_to_start',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='city',
            field=models.CharField(default='-', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='country',
            field=models.CharField(default='-', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='state',
            field=models.CharField(default='-', max_length=255),
            preserve_default=False,
        ),
    ]
