# Generated by Django 4.2.13 on 2024-06-18 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobmanager', '0008_jobapplication_available_to_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobmanager.location'),
        ),
    ]
